### ISSUE TITLE
[Request] Fleet and APM node renaming

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#1568] opened 2022-02-14 21:50 UTC
## Description

*In 8.0 the concept of an Integrations Server was introduced to replace and generalize the "fleet & APM node. We have some references in our feet-server documentation that would need to be upgraded*

## Collaboration

- The docs team will lead producing the content

* @nimarezainia  *

**Contact Person:**

## Suggested Target Release

*8.0*

## Stakeholders

*@nimarezainia*

**Comment by nimarezainia** [comment] 2022-02-14 21:54
On this page:  https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html

replace "3. Under APM & Fleet"  with  "3. Under Integrations Server"

Then replace the image with:

![image](https://user-images.githubusercontent.com/13442829/153952907-4f665251-136f-4551-bdd6-bc6ce566ea85.png)

**Comment by nimarezainia** [comment] 2022-02-14 21:57
On this page: https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html

In the "How to add a Fleet Server", the "Elasticsearch Service" tab would need to have the image updated:

![image](https://user-images.githubusercontent.com/13442829/153953239-e125931a-1344-4e66-a361-1599b06c5bb0.png)

**Comment by dedemorton** [comment] 2022-05-03 00:27
Duplicate of https://github.com/elastic/observability-docs/issues/1569.

We've fixed this in 8.1, but I'll keep 1569 open in case we want to fix this in 8.0, too.

**Closed by dedemorton** 2022-05-03 00:27 UTC
Labels: Team:Docs
