### ISSUE TITLE
Update docs: integration updates

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#512] opened 2021-04-14 15:48 UTC
Indicators for integration updates will be improving in future releases. We need to update the Elastic Agent Policy documentation to reflect these updates (added in https://github.com/elastic/observability-docs/pull/469).

@EricDavisX provided the following insight into the current process:

>   When the Integration 'packages' are released (the
packages are how the Integrations are delivered to the stack, via the on-line Elastic Package Registry
and the {kib} side Elastic Package Manager component). When a new Integration is released by Elastic
it will show up in the Integrations listing in {kib} after a restart (like during a stack upgrade) or
the user can trigger the refresh with the Fleet API, discussed in separate documentation.  In order
to take advantage of a newer Integration, there are a few steps a user must take as outlined below.
It is also recommended in larger deployments to try a new Integration with one sample Agent instead
of all that may apply.

> To check if a new Integration exists, follow the {policy} management documentation steps above to view
a {policy} with the Integration whose version is to be compared against the available Integrations
listing, and note the Integration version. It is the {fleet} application design team's desire to make
this as easy as possible, we intend to place an indicator next to the version citing it can be updated.
To manually confirm this however, browse to 'Integrations' in {kib} and scroll or browse to the noted
Integration and click on it. The latest version of the integration shipped to the stack by the Elastic
Package Registry is the only version that can be integrated into Agent policies at this point (though
older Integration versions in use on hosts by older Agent policies will continue to work). The version
is displayed on the right top side of the view, along with information about the Integration details.
Any {policies} that use the Integration are listed in the Policies tab. Likewise the 'Settings' tab
gives information and further access to manage the Integration's assets as they exist in the stack.
Compare the version noted from the Agent policy with what is listed in the Integration's view: If the
Integration has a newer version available, continue on to steps below to update it

This Kibana issue provides more details: https://github.com/elastic/kibana/issues/92612.

**Comment by dedemorton** [comment] 2021-08-30 17:00
This seems related to https://github.com/elastic/observability-docs/issues/900. Should we try to do them at the same time?

**Comment by bmorelli25** [comment] 2021-08-30 20:38
Yes

**Comment by dedemorton** [comment] 2021-09-01 01:22
@EricDavisX Unless I'm misunderstanding something here, I think the description of the upgrade functionality described in https://github.com/elastic/observability-docs/issues/900#issuecomment-899787651 is more up-to-date and accurate. Can I close this as a duplicate of #900?

**Comment by EricDavisX** [comment] 2021-09-01 02:45
Hi - indeed the copy I laid out was prior to the feature work done by the Fleet team, I would take the Engineering discussion and commentary over my old text for sure.  Let's close it

**Closed by EricDavisX** 2021-09-01 02:45 UTC
Labels: v7.14.0
