### ISSUE TITLE
[REQUEST]: Need the doc user roles for each managing (i.e. settings) section under observability provided in docs.

### ISSUE THREAD

**Issue by predogma** [elastic/observability-docs#3156] opened 2023-08-21 17:28 UTC
### Description

Need the user roles needed for each section under observability provided in docs.

Other than the [synthetics section](https://www.elastic.co/guide/en/observability/current/synthetics-feature-roles.html) of the Observability docs, there is not any clear indication of what roles a user needs in Kibana for read/managing other sections in Observability

In particular, privileges needed for editing 'Settings' for evey one of them.  With the superuser being reduced in permissions since 8.x, there are more and more cases related to unable to edit settings etc. in Kibana.

Ideally it needs to be at least highlighted at the [Get Started guide](https://www.elastic.co/guide/en/observability/current/observability-get-started.html) for each if not reource guide for each, logs for example

https://www.elastic.co/guide/en/observability/current/logs-metrics-get-started.html
https://www.elastic.co/guide/en/observability/current/logs-checklist.html

### Resources

https://www.elastic.co/guide/en/observability/current/observability-get-started.html
https://www.elastic.co/guide/en/observability/current/logs-metrics-get-started.html
https://www.elastic.co/guide/en/observability/current/ingest-traces.html
https://www.elastic.co/guide/en/observability/current/splunk-get-started.html

https://www.elastic.co/guide/en/observability/current/configure-settings.html
https://www.elastic.co/guide/en/observability/current/configure-uptime-settings.html
https://www.elastic.co/guide/en/observability/current/profiling-probabilistic-profiling.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @

**Stakeholders:**

**Comment by bmorelli25** [comment] 2023-10-25 22:53
Thank you for opening this issue, @predogma. I'm going to close this as a duplicate of https://github.com/elastic/observability-docs/issues/2991. We're almost ready to start looking back into #2991.

**Closed by bmorelli25** 2023-10-25 22:53 UTC
Labels: Team:Docs, request
