### ISSUE TITLE
Add doc for Alert Reason message and View In App URL rule variable support in alert actions  

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1705] opened 2022-03-22 12:40 UTC
## Description

Alert Reason message and View In App URL rule variables are now supported in alert actions. Need to add doc for those variables. 

https://github.com/elastic/kibana/issues/119090

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@fkanout 

## Suggested Target Release
8.2 (Please check with @fkanout on the feature completion status before proceeding with the documentation)

## Stakeholders
@emma-raffenne 
@simianhacker 
@vinaychandrasekhar

**Comment by colleenmcginnis** [comment] 2022-04-05 18:54
Duplicate of https://github.com/elastic/observability-docs/issues/1480?

**Comment by colleenmcginnis** [comment] 2022-04-05 19:58
Thanks for confirming @vinaychandrasekhar. I'm going to close here and we can track progress in #1480 (where I've updated the version tag). I also updated https://github.com/elastic/observability-dev/issues/2029#issuecomment-1075133906 for tracking purposes.

**Closed by colleenmcginnis** 2022-04-05 19:58 UTC
Labels: Team:Docs, v8.2.0
