### ISSUE TITLE
[REQUEST]: Infrastructure UI : Update docs for new host detail view

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3249] opened 2023-09-28 12:29 UTC
### Background

In 8.11, we will be replacing the existing host detail view with a faster loading and more consistent view than before - we need to update the documentation which refers to these old views:

**Old Version**

_Previous Host Detail View (via Inventory) - 8.10_
![8 10 - inventory to legacy host view](https://github.com/elastic/observability-docs/assets/117740680/c4113c92-7fc6-49a2-93ef-6b612a423998)

_Previous Host Detail View (via Host) - 8.10_
![8 9 - hosts to old detail view](https://github.com/elastic/observability-docs/assets/117740680/af79d290-debf-46c5-b2f1-4905838ea3ed)

**8.11 - Now**

_8.11 : Inventory to new host detail view_
![8 11 - inventory to new host view](https://github.com/elastic/observability-docs/assets/117740680/ad70c398-2e4a-4a9d-beaa-97b99e39ddaf)

_8.11 : Hosts to new host detail view_
![8 11 - host to detail view](https://github.com/elastic/observability-docs/assets/117740680/356ed9ea-a537-4b28-957e-9b28c2e2cc78)

### Docs to be updated
There appears to be one main place where the docs would be updated:

https://www.elastic.co/guide/en/observability/current/view-infrastructure-metrics.html#analyze-resource-metrics

<img width="953" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/547b4bbd-56ba-4e63-9a58-b80f628c147f">

### Where can I see the new functionality?

[Latest 8.11 build - Inventory - edge](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/inventory)
[Latest 8.11 build - Hosts - edge](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts)

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @smith @neptunian

**Comment by roshan-elastic** [comment] 2023-10-25 11:29
Hey @bmorelli25,

I was wondering if this is OK to be picked up for 8.11 (or if I need to do anything here other than wait)?

**Comment by bmorelli25** [comment] 2023-10-25 18:57
Thanks for the reminder on this one! Yes, this will be picked up for 8.11, and we'll get someone assigned to it soon.

**Comment by dedemorton** [comment] 2023-10-25 23:11
It makes sense for me to "own" this since I will be working on https://github.com/elastic/obs-docs-projects/issues/138 during this sprint.

**Comment by dedemorton** [comment] 2023-11-02 00:52
@roshan-elastic This looks like a duplicate of https://github.com/elastic/observability-docs/issues/3250.  Can we close this issue in favor of https://github.com/elastic/observability-docs/issues/3250, which seems more accurate (or is there something different here that I'm missing)?

**Comment by smith** [comment] 2023-11-02 04:28
@dedemorton I don't think it's a duplicate. #3250 was that we updated the flyout on the Inventory: [new inventory flyout](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/inventory?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1698898978558,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),timelineOpen:!f,view:map)&inventoryViewId=%270%27&assetDetailsFlyout=(detailsItemId:gke-edge-oblt-pool-2-9eb6f01b-wc7l)&assetDetails=(dateRange:(from:%272023-11-02T03:22:58.558Z%27,to:%272023-11-02T04:22:58.558Z%27),name:gke-edge-oblt-pool-2-9eb6f01b-wc7l))

This is about the detail view, which is the same component as the flyout but is the full page version you go to when you "open as page": [host detail view](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/detail/host/gke-edge-oblt-pool-2-9eb6f01b-wc7l?assetDetails=(dateRange:(from:%272023-11-02T03:22:58.558Z%27,to:%272023-11-02T04:22:58.558Z%27),name:gke-edge-oblt-pool-2-9eb6f01b-wc7l)&waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1698899110133,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map))

Which replaces the [old version](https://demo.elastic.co/app/metrics/detail/host/gke-demo-elastic-co-pool-5-29a9d3db-kdhb?_a=(autoReload:!f,refreshInterval:5000,time:(from:%272023-11-02T03:22:26.418Z%27,interval:%3E%3D1m,to:%272023-11-02T04:22:26.418Z%27))&waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1698899100816,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map))

**Comment by dedemorton** [comment] 2023-11-02 15:47
Thanks! I think my brain was too tired last night to see this. :-)

**Comment by roshan-elastic** [comment] 2023-11-06 12:03
:) yeah they're related but different

**Closed** 2023-11-06 21:10 UTC
Labels: docs, Team:Docs, Team:Infra Monitoring UI, Feature:ObsHosts, no-engineering-required, Area:MetricsUI
