### ISSUE TITLE
[Request]: Hosts List will now have active alert counts

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3627] opened 2024-02-15 10:18 UTC
### Description

The Hosts List will now show active alert counts for any hosts where an active alert was discovered:

https://github.com/elastic/kibana/assets/31922082/96794041-d129-49e2-920c-80b45c624144

[Edge build](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts)

### Resources

See PR:

- [ ] https://github.com/elastic/kibana/pull/176034

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Same cross all.

Live soon in serverless, 8.13 for stateful

See [existing docs](https://www.elastic.co/guide/en/observability/current/analyze-hosts.html)

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @MiriamAparicio @smith @crespocarlos

**Comment by roshan-elastic** [comment] 2024-02-15 10:18
cc @colleenmcginnis

**Comment by dedemorton** [comment] 2024-05-10 18:31
This looks like a duplicate of https://github.com/elastic/observability-docs/issues/3747, which I am actively working on right now.

**Comment by dedemorton** [comment] 2024-05-14 22:41
Closing as a duplicate. The changes are up in a PR here: https://github.com/elastic/observability-docs/pull/3879

**Closed by dedemorton** 2024-05-14 22:41 UTC
